-- ============================================================================
-- CONSOLIDATED REMAINDER MIGRATION
-- Generated by Gemini 3 (AI Cloud Agent)
-- Date: 2026-01-07
-- Purpose: Idempotently apply the desired schema state, ensuring no drift.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. EXTENSIONS
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ----------------------------------------------------------------------------
-- 2. CORE TABLES (Idempotent Creation)
-- ----------------------------------------------------------------------------

-- User Profiles
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Ensure all columns exist for user_profiles
DO $$ BEGIN
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS name TEXT;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS role TEXT;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS vertical TEXT;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS stack JSONB DEFAULT '{
    "code_repo": true,
    "issue_tracker": true,
    "doc_space": true,
    "ci_cd": true,
    "infra": true,
    "analytics": false
  }';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS tone TEXT DEFAULT 'balanced';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS risk_tolerance TEXT DEFAULT 'moderate';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS kpi_focus TEXT DEFAULT 'velocity';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS perspective TEXT DEFAULT 'founder';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS behavior_embedding VECTOR(1536);
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS brand_voice TEXT;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS company_context TEXT;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS preferred_models JSONB DEFAULT '["gpt-4-turbo", "claude-3-opus"]';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'UTC';
  
  -- Billing & Org columns (from 013)
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'free';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS subscription_tier TEXT DEFAULT 'free';
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS subscription_current_period_end TIMESTAMPTZ;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS org_id UUID;
  ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS premium_features JSONB DEFAULT '{
    "enabled": false,
    "voiceToText": false,
    "tokenLimit": 4000,
    "advancedFilters": false,
    "customPrompts": false
  }'::jsonb;
END $$;

-- Prompt Atoms
CREATE TABLE IF NOT EXISTS public.prompt_atoms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS name TEXT;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS category TEXT;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS version INT DEFAULT 1;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS system_prompt TEXT;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS constraints JSONB;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS examples JSONB;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS weight FLOAT DEFAULT 1.0;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS compatible_atoms TEXT[];
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS target_roles TEXT[];
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS target_verticals TEXT[];
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS usage_count INT DEFAULT 0;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS success_rate FLOAT DEFAULT 0.5;
  ALTER TABLE public.prompt_atoms ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;
END $$;

-- Vibe Configs
CREATE TABLE IF NOT EXISTS public.vibe_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS name TEXT;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS playfulness INT DEFAULT 50;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS revenue_focus INT DEFAULT 60;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS investor_perspective INT DEFAULT 40;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS selected_atoms UUID[];
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS custom_instructions TEXT;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS auto_suggest BOOLEAN DEFAULT true;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS approval_required BOOLEAN DEFAULT true;
  ALTER TABLE public.vibe_configs ADD COLUMN IF NOT EXISTS logging_level TEXT DEFAULT 'standard';
END $$;

-- Agent Runs
CREATE TABLE IF NOT EXISTS public.agent_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS trigger TEXT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS trigger_data JSONB;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS assembled_prompt TEXT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS selected_atoms UUID[];
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS vibe_config_snapshot JSONB;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS agent_type TEXT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS model_used TEXT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS generated_content JSONB;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS user_feedback TEXT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS feedback_detail TEXT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS tokens_used INT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS latency_ms INT;
  ALTER TABLE public.agent_runs ADD COLUMN IF NOT EXISTS cost_usd FLOAT;
END $$;

-- Background Events
CREATE TABLE IF NOT EXISTS public.background_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS event_type TEXT;
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS source TEXT;
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS event_data JSONB;
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS event_timestamp TIMESTAMP;
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS suggestion_generated BOOLEAN DEFAULT false;
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS suggestion_id UUID;
  ALTER TABLE public.background_events ADD COLUMN IF NOT EXISTS user_actioned BOOLEAN DEFAULT false;
END $$;

-- Organizations (Multi-Tenancy)
CREATE TABLE IF NOT EXISTS public.organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL, -- references auth.users
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS name TEXT;
  ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS slug TEXT;
  
  -- Add constraints if they don't exist
  BEGIN
    ALTER TABLE public.organizations ADD CONSTRAINT organizations_slug_key UNIQUE (slug);
  EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END;
END $$;

-- Organization Members
CREATE TABLE IF NOT EXISTS public.organization_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL, -- references auth.users
  role TEXT NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
  BEGIN
    ALTER TABLE public.organization_members ADD CONSTRAINT organization_members_org_id_user_id_key UNIQUE (org_id, user_id);
  EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END;
END $$;

-- Invitations
CREATE TABLE IF NOT EXISTS public.invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  invited_by UUID NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
  BEGIN
    ALTER TABLE public.invitations ADD CONSTRAINT invitations_org_id_email_key UNIQUE (org_id, email);
  EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END;
END $$;

-- Usage Metrics
CREATE TABLE IF NOT EXISTS public.usage_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  metric_type TEXT NOT NULL,
  metric_value INT NOT NULL DEFAULT 0,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
  BEGIN
    ALTER TABLE public.usage_metrics ADD CONSTRAINT usage_metrics_user_id_metric_type_period_start_key UNIQUE (user_id, metric_type, period_start);
  EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END;
END $$;

-- Template Tables (Simplified for brevity, assuming existing structure or creating basic)
CREATE TABLE IF NOT EXISTS public.user_template_customizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  template_id TEXT NOT NULL,
  milestone TEXT NOT NULL,
  custom_variables JSONB DEFAULT '{}'::jsonb,
  custom_instructions TEXT,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 3. INDEXES (Idempotent)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profiles_user_id_unique ON public.user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_subscription_status ON public.user_profiles(subscription_status);

CREATE INDEX IF NOT EXISTS idx_prompt_atoms_name_version ON public.prompt_atoms(name, version);
CREATE INDEX IF NOT EXISTS idx_prompt_atoms_category ON public.prompt_atoms(category);

CREATE INDEX IF NOT EXISTS idx_vibe_configs_user_id ON public.vibe_configs(user_id);

CREATE INDEX IF NOT EXISTS idx_agent_runs_user_id ON public.agent_runs(user_id);

CREATE INDEX IF NOT EXISTS idx_organizations_owner_id ON public.organizations(owner_id);
CREATE INDEX IF NOT EXISTS idx_organizations_slug ON public.organizations(slug);

-- ----------------------------------------------------------------------------
-- 4. FUNCTIONS & TRIGGERS (Idempotent)
-- ----------------------------------------------------------------------------

-- Update Updated At
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply Triggers (Drop first to avoid duplicates)
DROP TRIGGER IF EXISTS update_user_profiles_updated_at ON public.user_profiles;
CREATE TRIGGER update_user_profiles_updated_at BEFORE UPDATE ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_vibe_configs_updated_at ON public.vibe_configs;
CREATE TRIGGER update_vibe_configs_updated_at BEFORE UPDATE ON public.vibe_configs FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ----------------------------------------------------------------------------
-- 5. RLS & POLICIES (Idempotent)
-- ----------------------------------------------------------------------------

-- Enable RLS
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompt_atoms ENABLE ROW LEVEL SECURITY; -- CRITICAL FIX
ALTER TABLE public.vibe_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.background_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_metrics ENABLE ROW LEVEL SECURITY;

-- Policy Helper Macro (conceptually) - We write inline for compatibility
-- PROMPT ATOMS (Public Read, Admin Write)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public can view prompt atoms' AND tablename = 'prompt_atoms') THEN
    CREATE POLICY "Public can view prompt atoms" ON public.prompt_atoms FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service role can manage prompt atoms' AND tablename = 'prompt_atoms') THEN
    CREATE POLICY "Service role can manage prompt atoms" ON public.prompt_atoms FOR ALL USING (auth.jwt()->>'role' = 'service_role');
  END IF;
END $$;

-- USER PROFILES (Owner Access)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own profile' AND tablename = 'user_profiles') THEN
    CREATE POLICY "Users can view own profile" ON public.user_profiles FOR SELECT USING (auth.uid()::text = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update own profile' AND tablename = 'user_profiles') THEN
    CREATE POLICY "Users can update own profile" ON public.user_profiles FOR UPDATE USING (auth.uid()::text = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert own profile' AND tablename = 'user_profiles') THEN
    CREATE POLICY "Users can insert own profile" ON public.user_profiles FOR INSERT WITH CHECK (auth.uid()::text = user_id);
  END IF;
END $$;

-- ORGANIZATIONS
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own organizations' AND tablename = 'organizations') THEN
    CREATE POLICY "Users can view own organizations" ON public.organizations FOR SELECT USING (
      auth.uid() = owner_id OR
      EXISTS (SELECT 1 FROM public.organization_members WHERE org_id = id AND user_id = auth.uid())
    );
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can create organizations' AND tablename = 'organizations') THEN
    CREATE POLICY "Users can create organizations" ON public.organizations FOR INSERT WITH CHECK (auth.uid() = owner_id);
  END IF;
END $$;

-- VIBE CONFIGS
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own vibe configs' AND tablename = 'vibe_configs') THEN
    CREATE POLICY "Users can view own vibe configs" ON public.vibe_configs FOR SELECT USING (auth.uid()::text = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage own vibe configs' AND tablename = 'vibe_configs') THEN
    CREATE POLICY "Users can manage own vibe configs" ON public.vibe_configs FOR ALL USING (auth.uid()::text = user_id);
  END IF;
END $$;

-- AGENT RUNS
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own agent runs' AND tablename = 'agent_runs') THEN
    CREATE POLICY "Users can view own agent runs" ON public.agent_runs FOR SELECT USING (auth.uid()::text = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage own agent runs' AND tablename = 'agent_runs') THEN
    CREATE POLICY "Users can manage own agent runs" ON public.agent_runs FOR ALL USING (auth.uid()::text = user_id);
  END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 6. FINAL CLEANUP
-- ----------------------------------------------------------------------------
-- Ensure stats are up to date (optional, but good practice)
ANALYZE;
